# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e30baa06ad1c2e1585daa46a70d18139f23e921077b5b9c5c1502b7b3aaf26b860fc581a177da50298fcf84280ffd171fc59ff7e69f628a46b94161408e5a7cf

test:
  secret_key_base: d2334cbf1c3ea9925333eca522f2eaa8f1cd671efc4478d4afa008a4a0f95ca1234c70fac277acbef540e8b100cf1f95ebe8a758be0f7fcd1e2a302b4171b2fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
